### PR TITLE
Types package

### LINKED ISSUE #26: [question] publish npm package?
Hi,

have you thought of publishing your TypeScript Declaration Files to npm so that one could install it easily as a development dependency?

Best & thanks for putting those `.d.ts` files together.

### PR DESCRIPTION
**Pull request by twhiston**
Closes #26 

Updates examples to use the new `@types/maxmsp` package. Updated readme about how they work.

Added additional example of using Typescript to create objects in a max patcher.

Added Actions to test compilation and upload them on changes to the repo

### CODE REVIEW

**Comment by twhiston** [comment]
@ErnstHot please can you enable github actions on all branches of this repo? This PR should have triggered some new actions I added to test the code compilation but it has not. I don't have access to the repo settings to check/change this myself

**Comment by ErnstHot** [comment]
@twhiston I'm not sure exactly how this works, but for now I've created a minimally restrictive branch protection rule for all branches, which seems to have stopped GitHub from complaining.

**Comment by twhiston** [comment]
It doesn't seem to have triggered the tests still, but I will merge this into main and then see if they start running. If not I'll have a look into exactly what settings we need to change. It "just worked" on my fork so I'm not sure why that isn't the case here.

**Comment by twhiston** [comment]
@ErnstHot All good now, actions are running. https://github.com/ErnstHot/TypeScript-for-Max/actions/runs/4811721848

Thank you!

**Pull request merged**
